updated:docker

diff --git a/frontend/src/Dockerfile.prod b/frontend/src/Dockerfile.prod
--- a/frontend/src/Dockerfile.prod
+++ b/frontend/src/Dockerfile.prod
@@ -2,6 +2,7 @@ FROM node:22-slim
 
 WORKDIR /app
 
+
 # Declare the NODE_ENV
 ENV NODE_ENV=production
 # Add the Environment Port Variable
@@ -11,14 +12,15 @@ ENV PORT=3000
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
-# Copy package files first for better caching
-COPY package.json package-lock.json ./
-
-# Install dependencies
-RUN npm ci --legacy-peer-deps
-
-# Copy the rest of the application
 COPY . .
+
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    else echo "Lock file not found." && exit 1; \
+    fi
+ 
+RUN yarn install
 
 USER nextjs
 # Expose the Application Port 
@@ -26,5 +28,5 @@ EXPOSE 3000
 
 # Run the Application with "server.js" using node, which is 
 # Auto Generated by Standalone mode
-CMD ["npm", "start"]
+CMD ["yarn", "start"]
 # End (Block 3)
