added -- authentication

diff --git a/frontend/src/Dockerfile.prod b/frontend/src/Dockerfile.prod
--- a/frontend/src/Dockerfile.prod
+++ b/frontend/src/Dockerfile.prod
@@ -1,23 +1,12 @@
 FROM node:current-alpine AS deps
-# RUN apk add --no-cache libc6-compat
+
 WORKDIR /app
-COPY package.json yarn.lock* package-lock.json* ./
 
-RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    else echo "Lock file not found." && exit 1; \
-    fi
-
-# End (Block 1)
-
-
-# Start (Block 3) Create the Application Runner
-FROM node:current-alpine AS runner
-WORKDIR /app
 
 # Declare the NODE_ENV
-ENV NODE_ENV production
+ENV NODE_ENV=production
+# Add the Environment Port Variable
+ENV PORT=3000
 
 # Add the Group and User to Container 
 RUN addgroup --system --gid 1001 nodejs
@@ -25,13 +14,17 @@ RUN adduser --system --uid 1001 nextjs
 
 COPY . .
 
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    else echo "Lock file not found." && exit 1; \
+    fi
+ 
 RUN yarn install
 
 USER nextjs
 # Expose the Application Port 
 EXPOSE 3000
-# Add the Environment Port Variable
-ENV PORT 3000
 
 # Run the Application with "server.js" using node, which is 
 # Auto Generated by Standalone mode
