updated:docker

diff --git a/frontend/src/Dockerfile.prod b/frontend/src/Dockerfile.prod
--- a/frontend/src/Dockerfile.prod
+++ b/frontend/src/Dockerfile.prod
@@ -14,7 +14,12 @@ RUN adduser --system --uid 1001 nextjs
 
 COPY . .
 
-COPY package.json package-lock.json ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    else echo "Lock file not found." && exit 1; \
+    fi
+ 
 RUN npm ci --legacy-peer-deps
 
 USER nextjs
@@ -23,5 +28,5 @@ EXPOSE 3000
 
 # Run the Application with "server.js" using node, which is 
 # Auto Generated by Standalone mode
-CMD ["npm", "start"]
+CMD ["yarn", "start"]
 # End (Block 3)
