updated

diff --git a/frontend/src/Dockerfile.prod b/frontend/src/Dockerfile.prod
--- a/frontend/src/Dockerfile.prod
+++ b/frontend/src/Dockerfile.prod
@@ -2,9 +2,31 @@ FROM node:22-slim
 
 WORKDIR /app
 
-EXPOSE 3000
-COPY package.json package-lock.json ./
-RUN npm ci --legacy-peer-deps
+
+# Declare the NODE_ENV
+ENV NODE_ENV=production
+# Add the Environment Port Variable
+ENV PORT=3000
+
+# Add the Group and User to Container 
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
 COPY . .
-CMD ["npm", "start"]
+
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    else echo "Lock file not found." && exit 1; \
+    fi
+ 
+RUN yarn install
+
+USER nextjs
+# Expose the Application Port 
+EXPOSE 3000
+
+# Run the Application with "server.js" using node, which is 
+# Auto Generated by Standalone mode
+CMD ["yarn", "start"]
+# End (Block 3)
